In [1]:
pip install numpy

In [3]:
import numpy as np
print(np.__version__)

2.1.3


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [7]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np
arr=np.zeros((5,5))
print(arr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
import numpy as np
arr=np.ones((5,7))
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [11]:
import numpy as np
arr=np.full((4,7),9)
print(arr)

[[9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]]


In [12]:
import numpy as np
arr=np.empty((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
import numpy as np
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
import numpy as np
arr=np.arange(2,100,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [25]:
import numpy as np
Even=np.arange(2,200,3)
print(Even)

[  2   5   8  11  14  17  20  23  26  29  32  35  38  41  44  47  50  53
  56  59  62  65  68  71  74  77  80  83  86  89  92  95  98 101 104 107
 110 113 116 119 122 125 128 131 134 137 140 143 146 149 152 155 158 161
 164 167 170 173 176 179 182 185 188 191 194 197]


In [32]:
import numpy as np
arr=np.linspace(26,4,12)
print(arr)

[26. 24. 22. 20. 18. 16. 14. 12. 10.  8.  6.  4.]


In [33]:
import numpy as np
arr=np.random.rand(10)
print(arr)

[0.13258871 0.55239593 0.26080596 0.67878062 0.55595527 0.11347295
 0.83129456 0.84126292 0.45079796 0.07797954]


random is the module ,rand is the function# New Section

In [34]:
import numpy as np
arr=np.random.randn(10)
print(arr)

[-0.82623651  0.19431822  1.15543446  0.60929542  0.77339162 -0.94177783
  0.31171998  0.89944724 -0.76501146 -0.67316916]


In [61]:
import numpy as np
arr=np.random.randint(1)
print(arr)

0


In [72]:
import numpy as np
colours=["red","green","pink","orange","blue","wite","black"]
print(np.random.choice(colours,2))

['green' 'orange']


copy function

In [75]:
import numpy as np
arr=np.array([1,2,3])
new=arr.copy()
new[1]=100000
print("Copied value is :",arr)
print("Copied value is :",new)

Copied value is : [1 2 3]
Copied value is : [     1 100000      3]


view()

In [78]:
import numpy as np
arr=np.array([1,2,3])
new=arr.view()
new[2]=0.89
print("Array value is :",arr)
print("Viewed value is :",new)

Array value is : [1 2 0]
Viewed value is : [1 2 0]


In [81]:
import numpy as np
arr=np.array([5,12,56,47,3,6])
arr+=10
print("Updated array value is:",arr)

Updated array value is: [15 22 66 57 13 16]


In [83]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,0])
print(np.add(A,B))

[ 7  9 11 13  5]


In [95]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.add(A,B))
print(np.subtract(A,B))
print(np.multiply(A,B))
print(np.divide(A,B))

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [97]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,0])
print(np.dot(A,B))

80


In [104]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.sum(arr))
print(np.average(arr))
print(np.median(arr))
print(np.min(arr))
print(np.max(arr))
print(np.square(arr))
print(np.std(arr))
print(np.sort(arr))
print(np.unique(arr))

45
5.0
5.0
1
9
[ 1  4  9 16 25 36 49 64 81]
2.581988897471611
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [105]:
import numpy as np
arr=np.array([1,2,3,3,5,9,4,5,6,7,8,9])
print(np.unique(arr))

[1 2 3 4 5 6 7 8 9]


In [114]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.shape)
print(arr.size)
print(arr.itemsize)
print(arr.ndim)
print(arr.dtype)

(9,)
9
8
1
int64


In [123]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr.ndim)
print(arr[0,1])
print(arr[1,1])
print(arr[:,1])

(2, 4)
2
2
6
[2 6]


In [131]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,99,10,11,12,13,14,15])
print("Original array",arr)
new=arr.reshape(5,3)
print(new)

Original array [ 1  2  3  4  5  6  7  8 99 10 11 12 13 14 15]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 99]
 [10 11 12]
 [13 14 15]]
